version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: autonotes-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/data:/app/data
    networks:
      - autonotes-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: autonotes-client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - autonotes-network

networks:
  autonotes-network:
    driver: bridge
